# NumPy Array Slicing

## Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: `[start: end]`

We can also define the step, like this: `[start:end:step]`

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

Eg: Slice elements from index 1 to index 5 from the following array:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr[1:5])

[2 3 4 5]


> Note: The result includes the start index, but excludes the end index

Eg: Slice elements from index 4 to the end of the array:

In [2]:
print(arr[4:])

[5 6 7 8]


Eg: Slice elements from the beginning to the index 4 (not included)

In [3]:
print(arr[:4])

[1 2 3 4]


## Negative Slicing

Use the minus operator to refer to an index from the end:

Eg: Slice from the index 3 from the end to index 1 from the end:

In [4]:
print(arr[-3: -1])

[6 7]


## STEP

Use the `step` value to determine the step of the slicing.

Eg: Return every otehr element from index 1 to index 5:

In [5]:
print(arr[1:5:2])

[2 4]


Eg: Return every other element from teh entire array:

In [6]:
print(arr[::2])

[1 3 5 7]


## Slicing 2-D Arrays

Eg: From the 2nd element, slice elements from index 1 to index 4 (not included):

In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

print(arr[1, 1:4])

[ 8  9 10]


> Note: Remember that 2nd element has index 1

Eg: From both elements, return index 2:

In [8]:
print(arr[0:2, 2])

[3 9]


Eg: From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [9]:
print(arr[0:2, 1:4])

[[ 2  3  4]
 [ 8  9 10]]
