# NumPy Array Copy vs View

## The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original arrya.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view *does not own* the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## COPY:

Eg: Make a copy, change the original array, and display both arrays:

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

copyarr = arr.copy()

arr[0] = 10

print(arr)
print(copyarr)

[10  2  3]
[1 2 3]


>The copy SHOULD NOT be affected by the changes made to the original array.

## VIEW:

Eg: Make a view,  change the original array, and display both arrays:

In [3]:
import numpy as np

arr = np.array([1, 2, 4])
viewarr = arr.view()
arr[1] = 10

print(arr)
print(viewarr)

[ 1 10  4]
[ 1 10  4]


>The view SHOULD be affected by the changes made to the original array.

## Make Changes in the VIEW:

Eg: Make a view, change the view, and display both arrays:

In [5]:
import numpy as np

arr = np.array([1, 2, 3])
viewarr = arr.view()
viewarr[1] = 1000

print(arr)
print(viewarr)

[   1 1000    3]
[   1 1000    3]


> The original array SHOULD be affected by the changes made to the view.

## Check if Array Owns its Data

- copies *owns* the data, and view *does not own* the data

So, how to check this?

Every NumPy array has the attribute `base` that returns `None` if the array owns the data.

Otherwise, the `base` attribute refers to the original object.

In [6]:
import numpy as np

arr = np.array([1, 2, 3])

copyarr = arr.copy()
viewarr = arr.view()

print(copyarr.base)
print(viewarr.base)

None
[1 2 3]
