# NumPy Array Reshaping

## Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the no. of elements in each dimension.

By reshaping we can add or remove dimensions or change no. of elements in each dimension.

---

## Reshape from 1-D to 2-D

Eg: Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Reshape from 1-D to 3-D

Convert above array `arr` to 3-D array

The outermost dimension will have 2 arrays that contain 3 arrays, each with 2 elements:

In [6]:
threeDarr = arr.reshape(2, 3, 2)
print(threeDarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Can We Reshape Into any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3) # raises an error cuz we don't have enough elements in arr

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

## Returns Copy or View?

Eg: Check if the returned array is a copy or a view:

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base) # it returns the original array, so it is view

[1 2 3 4 5 6 7 8]


## Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass `-1` as the value, and NumPy will calculate this number for u.

Eg: Convert 1D array with 8 elements to 3D array with 2x2 elements:

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


> Note: We can not pass -1 to more than one dimension.

## Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use `reshape(-1)` to do this.

Eg: Convert the array into a 1D array:

In [17]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


> **Note**: There are a lot of functions for changing the shapes of arrays in numpy `flatten`, `ravel` and also for rearranging the elements `rot90`, `flip`, `fliplr`, `flipud` etc. These fall under Intermediate to Advanced section of numpy.