# NumPy Creating Arrays

## Create a NumPy ndarray Object

NumPy is used to work with arrays. The arrray object in NumPy is called `ndarray`.

We can create a NumPy `ndarray` object by using the `array()` function.

In [1]:
import numpy as np

arr = np.array([1, 2, 4, 5])

print(arr)

print(type(arr))

[1 2 4 5]
<class 'numpy.ndarray'>


> **type()**: this built-in Python func tells us the type of the object passed to it.

To create an `ndarray`, we can pass a list, tuple,, or any array-like object into the `array()` method, and it will be converted into an `ndarray`.

Eg:: use a tuple to create a NumPy array:

In [2]:
import numpy as np

arr = np.array((1, 2, 3))

print(arr)

[1 2 3]


## Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

> **nested array**: are arrays that have arrays as their elements

## 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Ech value in an array is a 0-D array

In [3]:
import numpy as np

arr = np.array(35)

print(arr)

35


## 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [4]:
import numpy as np

arr = np.array([1, 3, 5, 7])

print(arr)

[1 3 5 7]


## 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

> NumPy has a whole sub module dedicated towards matrix operation called `numpy.mat`

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 3, 1]])

print(arr)

[[1 2 3]
 [4 3 1]]


## 3-D Arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Check Number of Dimensions?

NumPy Arrays provides the `ndim` attribute that returns an integer that tells us how many dimensions the array have.

In [7]:
import numpy as np

arr1 = np.array(40)
arr2 = np.array([1, 2, 4])
arr3 = np.array([[1, 2, 3], [3, 5, 7]])
arr4 = np.array([[[1, 2, 3], [4, 3, 5]], [[4, 5, 3], [ 4, 2, 56]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


## Higher Dimensional Arrays

An array can have any no. of dimensions.

When the array is created, you can define the number of dimensions by using hte ndmin argument.

Eg: create an array with 5 dimesnions and verify that it has 5 dimensions:

In [8]:
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('no. of dimensions: ', arr.ndim)

[[[[[1 2 3 4]]]]]
no. of dimensions:  5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.