## Simple Arithmetic 

You could use arithmetic operators `+` `-` `*` `/` directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic *conditionally*.

> **Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.

All of the discussed arithmetic functions take a `where` parameter in which we can specify that condition.

---

## Addition

The `add()` function sums the content of two arrays, and return the results in a new array.

Eg: Add the values in arr1 to the values in arr2:

In [1]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


## Subtraction

The `subtract()` function subtracts the values from one array with the values from another array, and return the results in a new array.

In [3]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([20, 21, 22, 23, 24])

newarr = np.subtract(arr1, arr2) # arr1 - arr2

print(newarr)

[-10  -1   8  17  26]


## Multiplication

The `multiply()` function multiplies the values from one array with the values from another array, and return the results in a new array.

In [4]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([20, 21, 22, 23, 24])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200]


## Division

The `divide()` function divides values from one array with the values from another array, and return the results in a new array.

In [5]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([3, 5, 10, 8, 2])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.        ]


## Power 

The `power()` function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

In [6]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([3, 5, 6, 8, 2])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500]


## Remainder

Both the `mod()` and the `remainder()` functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [9]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([3, 7, 9, 8, 2])

newarr1 = np.mod(arr1, arr2)
newarr2 = np.remainder(arr1, arr2)

print(f"{newarr1}\n{newarr2}")

[1 6 3 0 0]
[1 6 3 0 0]


## Quotient and Mod

The `divmod()` function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [10]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([3, 7, 9, 8, 2])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25]), array([1, 6, 3, 0, 0]))


## Absolute Values

Both the `absolute()` and the `abs()` functions do the same absolute operation element-wise but we should use `absolute()` to avoid confusion with python's inbuilt `math.abs()`

In [11]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]
