# Random Numbers in NumPy

## What is a Random Number?

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

---

## Pseudo Random and True Random

Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a prgoram to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called *pseudo random*.

---

### Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless it is related to security (e.g., encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels (is basically traditional casino roulette wheel but intead of the physical ball handled by software))

Here we will be using pseudo random numbers...

---

## Generate Random Number

NumPy offers the `random` module to work with random numbers.

Eg: Generating a random integer from 0 to 100:

In [1]:
from numpy import random

x = random.randint(100)

print(x)

63


## Generate Random Float

The random module's `rand()` method retuns a random float between 0 and 1

In [3]:
from numpy import random

x = random.rand()

print(x)

0.32704947843501453


## Generate Random Array

In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

#### Integers

The `randint()` method takes a `size` parameter where you can specify the shape of an array.

Eg: Generate a 1-D array containing 5 random integers from 0 to 100:

In [4]:
from numpy import random

x = random.randint(100, size=(5))

print(x)

[22 96 12 34 87]


Eg: Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

In [5]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[ 3  1  1 13 53]
 [69 10 87 65  1]
 [87 68 86  5  4]]


#### Floats

The `rand()` method also allows you to specify the shape of the array.

Eg: Generate a 1-D array containing 5 random floats:

In [9]:
from numpy import random

x = random.rand(5)

print(x)

[0.3132281  0.98618021 0.41483188 0.65431269 0.09559069]


Eg: Generate a 2-D array with 3 rows, each containing 5 random numbers

In [10]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.06215761 0.27261206 0.84835481 0.66571895 0.2953799 ]
 [0.49020529 0.48728388 0.46503296 0.18960289 0.51759116]
 [0.0617695  0.36138671 0.85295465 0.77634293 0.66962164]]


## Generate Random Number From Array

The `choice()` method allows you to generate a random value based on an array of values.

The `choice()` method takes an array as a parameter and randomly returns one of the values.

Eg: Return one of the values in an array:

In [14]:
from numpy import random

x = random.choice([3, 5, 8, 9])

print(x)

8


The `choice()` method also allows you to return an *array* of values.

Add a `size` parameter to specify the shape of the array.

Eg: Generate a 2-D array that consists of the value in the array parameter (3, 5, 7, and 9):

In [15]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 9 7 7 3]
 [7 7 5 3 3]
 [7 9 5 3 9]]


# Two “randoms”
1.	Python standard library → import random
	-	Comes with Python.
	-	Simpler, slower, fewer options.

```python
Example:

import random
print(random.randint(1, 10))  # random int 1–10

```

2.	NumPy random module → import numpy as np then np.random
	-	Part of NumPy.
	-	Much faster (optimized in C).
	-	Supports arrays and scientific distributions.
	
```python
Example:

import numpy as np
print(np.random.randint(1, 10, size=5))  # 5 random ints
```

# When to use which?
-	Use random (Python’s) if you just need simple randomness for small tasks.
-	Use np.random if you’re doing data science, simulations, ML, or need random arrays.